# $Header: /space/home/eng/cjm/cvs/libdprt-ftspec/Makefile.common,v 1.1 2025-02-10 11:48:16 cjm Exp $

FTSPEC_HOME		= ftspec
LIBDPRT_FTSPEC_SRC_HOME	= $(LIBDPRT_SRC_HOME)/$(FTSPEC_HOME)
LIBDPRT_FTSPEC_BIN_HOME	= $(LIBDPRT_BIN_HOME)/$(FTSPEC_HOME)
LIBDPRT_FTSPEC_DOC_HOME	= $(LIBDPRT_DOC_HOME)/$(FTSPEC_HOME)

#
# $Log: not supported by cvs2svn $
#
